### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#1]
## Value proposition
 
**As a** user 
**I need** a list of available cryptocurrency's
**to be able to** get an overview of available cryptocurrency's and their price

## Description

List of Cryptocurrencies appears after a successful fetch and an input field to filter through the currency's.

Display Cryptocurrency's in its own card.
![image](https://user-images.githubusercontent.com/10044263/156727813-3672edb5-2133-4380-8044-28abcd86e26d.png)

Add Input field which will be the search field.
Use user input to filter dynamically through cryptocurrency list.
Filters the list of cryptocurrency's instantly and re-renders the list after every input.
![image](https://user-images.githubusercontent.com/10044263/156735204-3aa8a35a-2fdb-40a3-84a9-6e3946ce60d9.png)

## Acceptance Criteria
  - [x] List of currency's appears after a successful fetch
  - [x] Error shown if fetch fails
  - [x] Site is scroll able

Search
  - [x] Displays filtered list
  - [x] Convert user input and Cryptocurrency name to lowercase to compare them
  - [x] Update result list with every input event
  - [x] Input Validation: ^[a-zA-Z0-9_ ]+$ -- (Only letters and numbers)
  - [x] Error Handling
    - [x] Empty State: If nothing found show "Cant find the Cryptocurrency in the Database"
    - [x] Incorrect Input "Please don't enter special characters"

## Tasks

- [x]  Global styles
- [x]  Fetch (Currency(s)
- [x] components/Header
  - [x]  Storybook
  - [x]  Tests
  - [x]  Styling
- [x] components/Home
  - [x]  Storybook
  - [x]  Tests
  - [x]  Styling
  - [x] components/Search
  - [x]  Storybook
  - [x]  Tests
  - [x]  Styling
- [x]  Test on mobile (vertically and horizontally)
- [x] Add to app
