### ISSUE TITLE
Add Navigation

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#10]
## Value proposition
 
**As a** user 
**I need** to navigate between pages 
**to be able to** quickly select the page I want to be on

## Acceptance Criteria
- [ ] Navlinks between Main page and watchlist
- [ ] URL for watchlist= /watchlist
  
<img width="961" alt="image" src="https://user-images.githubusercontent.com/10044263/158335707-49d8ca8e-a1e5-4fb3-a78f-a8da520ec168.png">

## Tasks

  - [ ] Add components/Navigation 
    - [ ] Add Test and Storybook
  - [ ] Test on mobile (vertically and horizontally)
