### ISSUE TITLE
Add page Watchlist and the functionality to add cryptos to it 

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#11]
## Value proposition
 
**As a** user 
**I need** a page of my favorite crypto currency's 
**to be able to** quickly get an overview over my portfolio or cryptos I am interested in.

## Acceptance Criteria
- [ ] Add a toggle icon (fav-icon / star) to each CoinPage
- [ ] Add logic that if toggled coin will be visible in Watchlist page
- [ ] Add logic that if toggled again will be removed in Watchlist page
  
<img width="901" alt="image" src="https://user-images.githubusercontent.com/10044263/158334596-db55ef0a-3dd4-48a5-875c-d455345af42d.png">
<img width="450" alt="image" src="https://user-images.githubusercontent.com/10044263/158336168-b0420c8e-c0b5-45a3-97a7-a94d93c8f5c5.png">

## Tasks

  - [ ] Add pages/Watchlist 
    - [ ] Add Test and Storybook
  - [ ] Test on mobile (vertically and horizontally)
