### ISSUE TITLE
Add Local storage

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#12]
**As a** user 
**I need** to save the marked currencys
**to be able to** store them also when the app reloads or is re-opened

## Acceptance Criteria
  - [x]  Data stored in the local storage and they are available after reloading or re-opening the app
  - [x]  Only save bookmarked drinks in local storage

## Tasks
- [x] Add persists to hooks/useStore
