### ISSUE TITLE
Add zustand (statemanagment) and axios

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#19]
## Value proposition
 
**As a** user 
**I need** clean code and statemanagment
**to be able to** quickly understand the code

## Acceptance Criteria
- [x] Create useStore in hooks which manage all hooks

## Tasks

  - [x]  Install packages for axios and zustand
  - [x] Add useStore in the Hooks folder
    - [x] Build useStore with all states
    - [x] Use axios for fetches
    - [x] Replace all old states from all pages / components with the useStore states
  - [x] Check manually if all pages work correctly
  - [x] Check tests
