### ISSUE TITLE
Scroll to Top Button

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#21]
## Value proposition
 
**As a** user 
**I need** to navigate easily to the top
**to be able to** quickly interact with the webpage

## Acceptance Criteria
- [x] Button to scroll to top
- [x] Button should be shown after user scrolled down
  
<img width="485" alt="image" src="https://user-images.githubusercontent.com/10044263/159240379-a2fb734a-8f1a-442b-8603-da49398e2196.png">

## Tasks

  - [x] Add components/ScrollToTop 
    - [x] Add Test and Storybook
  - [x] Test on mobile (vertically and horizontally)
