### ISSUE TITLE
Add cryptocurrency exchange/converter 

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#22]
## Value proposition
 
**As a** user 
**I need** to convert prices
**to be able to** calculate how much the value is in my currency or the crypto currency

## Acceptance Criteria
- [x] Add convert (Crypto to currency) or (Currency to crypto) For example 1 ETH convert to BTC => 0.003 BTC
- [x] Add input fields to show exchange / converted
- [x] Add dropdown menus (From input) and (To input) to select currencys you want to convert from / to.
- [x] Show current exchange rate of selected cryptocurrency.
- [x] Inputfields only allow numbers
    - [x] Add error if anything but number is typed in
<img width="400" alt="image" src="https://user-images.githubusercontent.com/10044263/159251145-802e02d6-c997-4c86-a2ea-128c82235b36.png">

## Tasks

  - [x] Add components/converter
  - [x] Test on mobile (vertically and horizontally)
