### ISSUE TITLE
Dashboard - Search input (filter for currency)

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#3]
## Value proposition
 
**As a user** I want to search for a certain cryptocurrency's
**to be able to** see the price of the cryptocurrency's which I am interested in.

## Description

Add Input field which will be the search field.
Use user input to filter through cryptocurrency list -> Display the currency's user is interested in
![image](https://user-images.githubusercontent.com/10044263/156581091-aed977f9-3e0c-45a1-9ae8-bfe312fc448c.png)

## Acceptance Criteria
  - [ ] Hide / Show Search bar
  - [ ] Displays filtered list
  - [ ] Error shown if wrong user input
  - [ ] Error shown if no currency's found

## Tasks

- [ ]  Global styles
- [ ]  Zustand
- [ ]  Axios
- [ ] components/Search
  - [ ]  Storybook
  - [ ]  Tests
  - [ ]  Styling
- [ ]  Test on mobile (vertically and horizontally)
- [ ] Add to app
