### ISSUE TITLE
Add dropdown menu to choose currency (eur/usd...)

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#32]
## Value proposition
 
**As a** user 
**I need** to change the currency in different fiats
**to be able to** check the prices in different currencys

## Description
Dropdown menu to change the fiat to see the prices in currency of choice 
![image](https://user-images.githubusercontent.com/10044263/156735090-01ade868-077c-42f6-a3eb-27866039bc5c.png)

## Acceptance Criteria
  - [ ] Dropdown menu which shows different currency's
    - [ ] Searchable for currency's
    - [ ] Click on currency should change prices into selected currency

## Tasks

- [ ] src/pages/HomePage (Add dropdown react select)
- [ ] Build component for react select field
