### ISSUE TITLE
Scroll to top on every transition

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#37]
## Value proposition
 
**As a** user 
**I need** the page to start at the top
**to be able to** to interact normally with the webpage

## Acceptance Criteria
- [x] Should be a hidden script to automatically start page at top

## Tasks

  - [x] Add components/GlobalScrollToTop 
  - [x] Test on mobile
