### ISSUE TITLE
Sortable Grid

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#4]
## Value proposition
 
**As a user** I want to see a sorted list to get the (cheapest to most expensive) or (Bullish coins to lowest % coins of the day)
**to be able to** see the price of the cryptocurrency's which I am interested in.

## Description
Allow Sorting in Grid by “Price”, “% Value” both in ascending and descending order.
![image](https://user-images.githubusercontent.com/10044263/156581091-aed977f9-3e0c-45a1-9ae8-bfe312fc448c.png)

## Acceptance Criteria
  - [ ] First click: ascending
  - [ ] Second click: descending
  - [ ] Third click: disable sort

## Tasks

- [ ]  Global styles
- [ ]  Zustand
- [ ]  Axios
- [ ] components/Dashboard
  - [ ]  Storybook
  - [ ]  Tests
  - [ ]  Styling
- [ ]  Test on mobile (vertically and horizontally)
- [ ] Add to app
