### ISSUE TITLE
Extra page for Cryptocurrency details -- for each currency

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#5]
## Value proposition
 
**As a** user 
**I need** to have the possiblity to check a certain cryptocurrency for more details
**to be able to** have a better overview

## Acceptance Criteria
  - [x] If you click on a card of a cryptocurrency the detailed site will open.
  - [x] Clicking on the <- will take you back to the main page.
  - [x] Clicking on the <- will take you back to the main page.
  - [x] Render a chart which shows the price of the coin
<img width="945" alt="image" src="https://user-images.githubusercontent.com/10044263/157473214-ba06ff8e-5c08-4208-bdd2-a3e39b081d21.png">

## Tasks

- [ ]  Add new Page with details about coins
  - [ ]  Add Chart component
  - [ ] Add variable route to details - Each coin has a variable link -- /coins/bitcoin
- [ ]  Add React Router.
- [ ] components/coins/
  - [ ]  Storybook
  - [ ]  Tests
  - [ ]  Styling
- [ ]  Test on mobile (vertically and horizontally)
- [ ] Check accessibility (aria-label for the <- button)
