### ISSUE TITLE
Add Chart component to crypto currency detail page

### ISSUE THREAD

**Issue by teifler** [teifler/capstone-project#9]
## Value proposition
 
**As a** user 
**I need** to have the possibility to see a price chart of a certain crypto currency
**to be able to** have a better overview over the price

## Acceptance Criteria
  - [x] Render a chart which shows the price of coin which is selected
  - [x] Be able to filter the chart via timestamp (24h, 7D, 1M, 3M, 1Y)
  - [x] If 24h is selected show the time instead of the date 
<img width="929" alt="image" src="https://user-images.githubusercontent.com/10044263/158327477-4295478f-7ad1-4b4d-8f11-d7978df0587d.png">

## Tasks
  - [x] Research Charts (ChartJS vs rechart)
  - [x] Create chart component in components/CryptoChart.js
  - [x] Add chart component to /components/CoinPage.js
- [x] components/CryptoChart.js
  - [x]  Styling
- [x]  Test on mobile (vertically and horizontally)
